smile = "&eâ˜»"
smile1 = "&eâ˜º"
sun = "&eâ˜€"
moon = "â˜½"
cloud = "&7â˜"
rain = "&9â˜”"
lightning = "&eâš¡"
snow = "â„"
snowman = "â›„"
comet = "&6â˜„"
music = "&dâ™«"
music1 = "&dâ™ª"
clubs = "&8â™£"
diamond = "&câ™¦"
spades = "&8â™ "
tick = "&aâœ”"
cross = "&câœ–"
star = "&eâ˜…"
king = "&6â™›"
queen = "&6â™š"
arrow = "&8â¸"
flower = "&aâœ¿"
triangle = "&câ–²"
tm = "â„¢"
sad = "&eâ˜¹"
infinity = "&bâˆ"
mail = "âœ‰"
scissors = "&7âœ‚"
dot = "&0â—"
plane = "âœˆ"
peace = "&eâ˜®"
wave = "&bâ‰ˆ"
yinyang = "â˜¯"
warning = "&câš "
clock = "&9âŒš"
anchor = "&8âš“"
sword = "&7ğŸ—¡"
bow = "&6ğŸ¹"
swords = "&7âš”"
axes = "&8âš’"
potion = "&dğŸ§ª"
potion1 = "&5âš—"
pickaxe = "&3â›"
fishing = "&9ğŸ£"
axe = "&7ğŸª“"
trident = "&3"
bomb = "&8â—&7~&6*"
pencil = "&eâœ"
tea = "â˜•"
leaf = "&aâ˜˜"
male = "&9â™‚"
female = "&dâ™€"
stop = "&c&lâŒ€"
house = "&6&lÛ©"
butterfly = "&bÎµ&3Ñ—&bĞ·"
chess = "&0â™š&fâ™›"
eyes = "Ê˜Ê˜"
info = "&bâ„¹"
gender3 = "&5âš¥"
dice = "âš‚"
flower1 = "&dâ‰"
number = "&7â„–"
money = "&2[*&2&lâ€&2*]"
weight = "&8â– &7&m--&8â– "
glasses = "&7&lâŒ&0âœª&7-&0âœª"
left = "&b&lâ†"
right = "&b&lâ†’"
up = "&b&lâ†‘"
down = "&b&lâ†“"
star1 = "&eâœ­"
snail = "&b@&3&l-&bâ€™â€™"
recycle = "&aâ™»"
half = "&7Â½"
quarter = "&7Â¼"
fire = "&6ğŸ”¥"
jar = "&6&lâš±"
third = "&7â…“"
eightball = "â‘§"
person = "&e&lì›ƒ"
wheelchair = "&b&lâ™¿"
toxic = "&c&lâ˜£"
cursor = "â¢"
turtle = "&aâ€¢Â¤"
square = "&6â– "
timer = "âŒ›"
